### ISSUE TITLE
Fails to build with gemmi 0.6.2

### ISSUE THREAD

**Issue by merkys** [samuelflores/molmodel#10]
molmodel 3.1.0 does not build with gemmi 0.6.2:
```
/home/merkys/molmodel-3.1.0/src/PDBReader.cpp: In function 
'gemmi::Structure getStructureFromFile(const std::string&)':
/home/merkys/molmodel-3.1.0/src/PDBReader.cpp:98:29: error: 
'make_structure_from_block' is not a member of 'gemmi::impl'; did you 
mean 'gemmi::make_structure_from_block'?
   98 |         return gemmi::impl::make_structure_from_block ( 
gemmiDoc.blocks.at(0) );
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gemmi/mmread.hpp:13,
                 from 
/home/merkys/molmodel-3.1.0/./include/molmodel/internal/Compound.h:48,
                 from 
/home/merkys/molmodel-3.1.0/./include/molmodel/internal/CompoundSystem.h:6,
                 from 
/home/merkys/molmodel-3.1.0/./include/molmodel/internal/PDBReader.h:36,
                 from /home/merkys/molmodel-3.1.0/src/PDBReader.cpp:33:
/usr/include/gemmi/mmcif.hpp:15:21: note: 
'gemmi::make_structure_from_block' declared here
   15 | GEMMI_DLL Structure make_structure_from_block(const cif::Block& 
block);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/SimTKmolmodel.dir/build.make:219: 
CMakeFiles/SimTKmolmodel.dir/src/PDBReader.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/merkys/molmodel-3.1.0/src/Pdb.cpp: In function 'gemmi::Structure 
gemmiStructFromDoc(const gemmi::cif::Document&)':
/home/merkys/molmodel-3.1.0/src/Pdb.cpp:39:25: error: 
'make_structure_from_block' is not a member of 'gemmi::impl'; did you 
mean 'gemmi::make_structure_from_block'?
   39 |     return 
gemmi::impl::make_structure_from_block(doc.blocks.front());
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gemmi/mmread.hpp:13,
                 from 
/home/merkys/molmodel-3.1.0/./include/molmodel/internal/Compound.h:48,
                 from 
/home/merkys/molmodel-3.1.0/./include/molmodel/internal/Pdb.h:6,
                 from /home/merkys/molmodel-3.1.0/src/Pdb.cpp:4:
/usr/include/gemmi/mmcif.hpp:15:21: note: 
'gemmi::make_structure_from_block' declared here
   15 | GEMMI_DLL Structure make_structure_from_block(const cif::Block& 
block);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MadCatX** [comment]
Fixed in master

**Comment by merkys** [comment]
I confirm that commit f8492b9346dd8a2c32e3aa815294a3248b051d1f fixed the issue. Thanks a lot!

**Comment by samuelflores** [comment]
Hej Andrius,

glad Michal was able to help you with that.

Are you thinking about doing an update for debian? Would be pretty cool. We
are soon to publish a paper showing how to trace the viral genome through
low resolution density maps, using the current version of MMB.

sam

**Comment by merkys** [comment]
Hi @samuelflores, molmodel and MMB both are already up-to-date in Debian. I am currently doing some updates of their dependencies like gemmi and OpenMM, I will let you know should I encounter any incompatibilities.
